# Generated by Django 3.1.7 on 2023-03-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonMainlandTravelData',
            fields=[
                ('DATE', models.DateField(db_column='日期', primary_key=True, serialize=False)),
                ('SUM', models.IntegerField(db_column='合计')),
                ('FOREIGN', models.IntegerField(db_column='外国人')),
                ('HM', models.IntegerField(db_column='港澳')),
                ('TW', models.IntegerField(db_column='台湾省')),
            ],
            options={
                'db_table': 'data_nmainland',
            },
        ),
    ]
