# Generated by Django 3.1.7 on 2023-03-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignTravelData',
            fields=[
                ('DATE', models.DateField(db_column='日期', primary_key=True, serialize=False)),
                ('Japan', models.IntegerField(db_column='日本')),
                ('Singapore', models.IntegerField(db_column='新加坡')),
                ('Tailand', models.IntegerField(db_column='泰国')),
                ('Korea', models.IntegerField(db_column='韩国')),
                ('US', models.IntegerField(db_column='美国')),
                ('Canada', models.IntegerField(db_column='加拿大')),
                ('UK', models.IntegerField(db_column='英国')),
                ('Franch', models.IntegerField(db_column='法国')),
                ('German', models.IntegerField(db_column='德国')),
                ('Italy', models.IntegerField(db_column='意大利')),
                ('Russia', models.IntegerField(db_column='俄罗斯')),
                ('Australia', models.IntegerField(db_column='澳大利亚')),
                ('NewZealand', models.IntegerField(db_column='新西兰')),
            ],
            options={
                'db_table': 'data_foreign',
            },
        ),
        migrations.AlterModelTable(
            name='nonmainlandtraveldata',
            table='data_nonmainland',
        ),
    ]
