# Generated by Django 3.1.7 on 2023-04-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230330_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelData',
            fields=[
                ('DATE', models.DateField(db_column='日期', primary_key=True, serialize=False)),
                ('avg_rent_rate', models.FloatField(db_column='星级平均出租率')),
                ('avg_price', models.IntegerField(db_column='星级平均房价')),
                ('avg_price_inc', models.FloatField(db_column='星级平均房价增长')),
                ('avg_rent_rate_5', models.FloatField(db_column='五星级平均出租率')),
                ('avg_price_5', models.IntegerField(db_column='五星级平均房价')),
                ('avg_price_inc_5', models.FloatField(db_column='五星级平均房价增长')),
            ],
        ),
    ]
