# Generated by Django 3.1.7 on 2023-04-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hoteldata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hoteldata',
            table='data_hotel',
        ),
    ]
