# Generated by Django 3.1.7 on 2023-04-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230406_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldata',
            name='avg_price_inc',
        ),
        migrations.RemoveField(
            model_name='hoteldata',
            name='avg_price_inc_5',
        ),
    ]
